# Basic Usage Demo
This notebook goes over how to load data using the `covid19pandas` package. We will cover the many loading options available.

First, import the package.

In [1]:
import covid19pandas as cod

## Data source options
Our package provides access to data from both [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19) and [The New York Times](https://github.com/nytimes/covid-19-data). Here are some details about both datasets:
#### Johns Hopkins
- Function for access: `get_data_jhu`
- Provides both global and US data
- US data is broken down into states and counties
- For global data, provides confirmed cases, deaths, and recovered counts
- For US data, provides only confirmed cases and deaths counts.

#### The New York Times
- Function for access: `get_data_nyt`
- Provides only US data
- Has both state and county-level data
- Provides confirmed cases and deaths counts.

We provide both data sources for comparison, as they aggregate data from different sources.

Note: Johns Hopkins [has stated](https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-606354840) that the reason they do not provide recovered counts for their US-specific data is that they cannot find a reliable source for recovered counts at the county level.

In [2]:
cod.get_data_jhu()

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,date,Province/State,Country/Region,Lat,Long,cases,deaths,recovered
0,2020-01-22,Anhui,China,31.825700,117.226400,1.0,0.0,0.0
1,2020-01-22,Beijing,China,40.182400,116.414200,14.0,0.0,0.0
2,2020-01-22,Chongqing,China,30.057200,107.874000,6.0,0.0,0.0
3,2020-01-22,Fujian,China,26.078900,117.987400,1.0,0.0,0.0
4,2020-01-22,Guangdong,China,23.341700,113.424400,26.0,0.0,0.0
5,2020-01-22,Guangxi,China,23.829800,108.788100,2.0,0.0,0.0
6,2020-01-22,Guizhou,China,26.815400,106.874800,1.0,0.0,0.0
7,2020-01-22,Hainan,China,19.195900,109.745300,4.0,0.0,0.0
8,2020-01-22,Hebei,China,39.549000,116.130600,1.0,0.0,0.0
9,2020-01-22,Henan,China,33.882000,113.614000,5.0,0.0,0.0
10,2020-01-22,Hubei,China,30.975600,112.270700,444.0,17.0,28.0
11,2020-01-22,Hunan,China,27.610400,111.708800,4.0,0.0,0.0
12,2020-01-22,Jiangsu,China,32.971100,119.455000,1.0,0.0,0.0
13,2020-01-22,Jiangxi,China,27.614000,115.722100,2.0,0.0,0.0
14,2020-01-22,Liaoning,China,41.295600,122.608500,2.0,0.0,0.0
15,2020-01-22,Macau,China,22.166700,113.550000,1.0,0.0,0.0
16,2020-01-22,Ningxia,China,37.269200,106.165500,1.0,0.0,0.0
17,2020-01-22,Shandong,China,36.342700,118.149800,2.0,0.0,0.0
18,2020-01-22,Shanghai,China,31.202000,121.449100,9.0,0.0,0.0
19,2020-01-22,Shanxi,China,37.577700,112.292200,1.0,0.0,0.0
20,2020-01-22,Sichuan,China,30.617100,102.710300,5.0,0.0,0.0
21,2020-01-22,Tianjin,China,39.305400,117.323000,4.0,0.0,0.0
22,2020-01-22,Yunnan,China,24.974000,101.487000,1.0,0.0,0.0
23,2020-01-22,Zhejiang,China,29.183200,120.093400,10.0,0.0,0.0
24,2020-01-22,NaN,Japan,36.000000,138.000000,2.0,0.0,0.0
25,2020-01-22,NaN,"Korea, South",36.000000,128.000000,1.0,0.0,0.0
26,2020-01-22,NaN,Taiwan*,23.700000,121.000000,1.0,0.0,0.0
27,2020-01-22,NaN,Thailand,15.000000,101.000000,2.0,0.0,0.0
28,2020-01-22,NaN,US,37.090200,-95.712900,1.0,0.0,0.0
29,2020-01-23,Anhui,China,31.825700,117.226400,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...
8436,2020-03-31,NaN,Syria,34.802075,38.996815,10.0,2.0,0.0
8437,2020-03-31,NaN,Taiwan*,23.700000,121.000000,322.0,5.0,39.0
8438,2020-03-31,NaN,Tanzania,-6.369000,34.888800,19.0,1.0,1.0
8439,2020-03-31,NaN,Thailand,15.000000,101.000000,1651.0,10.0,342.0
8440,2020-03-31,NaN,Timor-Leste,-8.874217,125.727539,1.0,0.0,0.0
8441,2020-03-31,NaN,Togo,8.619500,0.824800,34.0,1.0,10.0
8442,2020-03-31,NaN,Trinidad and Tobago,10.691800,-61.222500,87.0,3.0,1.0
8443,2020-03-31,NaN,Tunisia,34.000000,9.000000,394.0,10.0,3.0
8444,2020-03-31,NaN,Turkey,38.963700,35.243300,13531.0,214.0,243.0
8445,2020-03-31,NaN,US,37.090200,-95.712900,188172.0,3873.0,7024.0
8446,2020-03-31,NaN,Uganda,1.000000,32.000000,44.0,0.0,0.0
8447,2020-03-31,NaN,Ukraine,48.379400,31.165600,645.0,17.0,10.0
8448,2020-03-31,NaN,United Arab Emirates,24.000000,54.000000,664.0,6.0,61.0
8449,2020-03-31,NaN,United Kingdom,55.378100,-3.436000,25150.0,1789.0,135.0
8450,2020-03-31,Anguilla,United Kingdom,18.220600,-63.068600,2.0,0.0,0.0
8451,2020-03-31,Bermuda,United Kingdom,32.307800,-64.750500,32.0,0.0,10.0
8452,2020-03-31,British Virgin Islands,United Kingdom,18.420700,-64.640000,3.0,0.0,0.0
8453,2020-03-31,Cayman Islands,United Kingdom,19.313300,-81.254600,14.0,1.0,0.0
8454,2020-03-31,Channel Islands,United Kingdom,49.372300,-2.364400,141.0,3.0,0.0
8455,2020-03-31,Gibraltar,United Kingdom,36.140800,-5.353600,69.0,0.0,34.0
8456,2020-03-31,Isle of Man,United Kingdom,54.236100,-4.548100,60.0,0.0,0.0
8457,2020-03-31,Montserrat,United Kingdom,16.742500,-62.187400,5.0,0.0,0.0
8458,2020-03-31,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,5.0,0.0,0.0
8459,2020-03-31,NaN,Uruguay,-32.522800,-55.765800,338.0,1.0,41.0
8460,2020-03-31,NaN,Uzbekistan,41.377500,64.585300,172.0,2.0,7.0
8461,2020-03-31,NaN,Venezuela,6.423800,-66.589700,135.0,3.0,39.0
8462,2020-03-31,NaN,Vietnam,16.000000,108.000000,212.0,0.0,58.0
8463,2020-03-31,NaN,West Bank and Gaza,31.952200,35.233200,119.0,1.0,18.0
8464,2020-03-31,NaN,Zambia,-15.416700,28.283300,35.0,0.0,0.0
8465,2020-03-31,NaN,Zimbabwe,-20.000000,30.000000,8.0,1.0,0.0

In [3]:
cod.get_data_nyt()

These data were obtained from The New York Times (https://github.com/nytimes/covid-19-data).

            date                     state  fips  cases  deaths
0     2020-01-21                Washington    53      1       0
1     2020-01-22                Washington    53      1       0
2     2020-01-23                Washington    53      1       0
3     2020-01-24                  Illinois    17      1       0
4     2020-01-24                Washington    53      1       0
5     2020-01-25                California     6      1       0
6     2020-01-25                  Illinois    17      1       0
7     2020-01-25                Washington    53      1       0
8     2020-01-26                   Arizona     4      1       0
9     2020-01-26                California     6      2       0
10    2020-01-26                  Illinois    17      1       0
11    2020-01-26                Washington    53      1       0
12    2020-01-27                   Arizona     4      1       0
13    2020-01-27                California     6      2       0
14    2020-01-27                  Illinois    17      1       0
15    2020-01-27                Washington    53      1       0
16    2020-01-28                   Arizona     4      1       0
17    2020-01-28                California     6      2       0
18    2020-01-28                  Illinois    17      1       0
19    2020-01-28                Washington    53      1       0
20    2020-01-29                   Arizona     4      1       0
21    2020-01-29                California     6      2       0
22    2020-01-29                  Illinois    17      1       0
23    2020-01-29                Washington    53      1       0
24    2020-01-30                   Arizona     4      1       0
25    2020-01-30                California     6      2       0
26    2020-01-30                  Illinois    17      2       0
27    2020-01-30                Washington    53      1       0
28    2020-01-31                   Arizona     4      1       0
29    2020-01-31                California     6      3       0
...          ...                       ...   ...    ...     ...
1524  2020-03-30               Mississippi    28    848      16
1525  2020-03-30                  Missouri    29   1050      13
1526  2020-03-30                   Montana    30    177       4
1527  2020-03-30                  Nebraska    31    185       3
1528  2020-03-30                    Nevada    32   1044      18
1529  2020-03-30             New Hampshire    33    314       3
1530  2020-03-30                New Jersey    34  16636     199
1531  2020-03-30                New Mexico    35    281       4
1532  2020-03-30                  New York    36  67174    1224
1533  2020-03-30            North Carolina    37   1304       6
1534  2020-03-30              North Dakota    38    109       3
1535  2020-03-30  Northern Mariana Islands    69      2       0
1536  2020-03-30                      Ohio    39   1933      40
1537  2020-03-30                  Oklahoma    40    481      17
1538  2020-03-30                    Oregon    41    606      16
1539  2020-03-30              Pennsylvania    42   4156      48
1540  2020-03-30               Puerto Rico    72    174       6
1541  2020-03-30              Rhode Island    44    408       4
1542  2020-03-30            South Carolina    45    925      18
1543  2020-03-30              South Dakota    46    101       1
1544  2020-03-30                 Tennessee    47   1834      13
1545  2020-03-30                     Texas    48   3043      46
1546  2020-03-30                      Utah    49    806       4
1547  2020-03-30                   Vermont    50    256      12
1548  2020-03-30            Virgin Islands    78     30       0
1549  2020-03-30                  Virginia    51   1021      26
1550  2020-03-30                Washington    53   5179     221
1551  2020-03-30             West Virginia    54    145       1
1552  2020-03-30                 Wisconsin    55   1267      20
1553  2020-03-30                   Wyoming    56     95       0

[1554 rows x 5 columns]

## Data type options
By default, our package will return counts cases, deaths, and recovered (the last if it's available). We call these "data types". You may want a table that only has one data type. To get a table with just one data type, pass that data type to the `data_type` parameter.

For example, to get just the counts of confirmed cases:

In [4]:
cod.get_data_jhu(data_type="cases")

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,date,Province/State,Country/Region,Lat,Long,cases
0,2020-01-22,Anhui,China,31.825700,117.226400,1
1,2020-01-22,Beijing,China,40.182400,116.414200,14
2,2020-01-22,Chongqing,China,30.057200,107.874000,6
3,2020-01-22,Fujian,China,26.078900,117.987400,1
4,2020-01-22,Guangdong,China,23.341700,113.424400,26
5,2020-01-22,Guangxi,China,23.829800,108.788100,2
6,2020-01-22,Guizhou,China,26.815400,106.874800,1
7,2020-01-22,Hainan,China,19.195900,109.745300,4
8,2020-01-22,Hebei,China,39.549000,116.130600,1
9,2020-01-22,Henan,China,33.882000,113.614000,5
10,2020-01-22,Hubei,China,30.975600,112.270700,444
11,2020-01-22,Hunan,China,27.610400,111.708800,4
12,2020-01-22,Jiangsu,China,32.971100,119.455000,1
13,2020-01-22,Jiangxi,China,27.614000,115.722100,2
14,2020-01-22,Liaoning,China,41.295600,122.608500,2
15,2020-01-22,Macau,China,22.166700,113.550000,1
16,2020-01-22,Ningxia,China,37.269200,106.165500,1
17,2020-01-22,Shandong,China,36.342700,118.149800,2
18,2020-01-22,Shanghai,China,31.202000,121.449100,9
19,2020-01-22,Shanxi,China,37.577700,112.292200,1
20,2020-01-22,Sichuan,China,30.617100,102.710300,5
21,2020-01-22,Tianjin,China,39.305400,117.323000,4
22,2020-01-22,Yunnan,China,24.974000,101.487000,1
23,2020-01-22,Zhejiang,China,29.183200,120.093400,10
24,2020-01-22,NaN,Japan,36.000000,138.000000,2
25,2020-01-22,NaN,"Korea, South",36.000000,128.000000,1
26,2020-01-22,NaN,Taiwan*,23.700000,121.000000,1
27,2020-01-22,NaN,Thailand,15.000000,101.000000,2
28,2020-01-22,NaN,US,37.090200,-95.712900,1
29,2020-01-23,Anhui,China,31.825700,117.226400,9
...,...,...,...,...,...,...
8377,2020-03-31,NaN,Syria,34.802075,38.996815,10
8378,2020-03-31,NaN,Taiwan*,23.700000,121.000000,322
8379,2020-03-31,NaN,Tanzania,-6.369000,34.888800,19
8380,2020-03-31,NaN,Thailand,15.000000,101.000000,1651
8381,2020-03-31,NaN,Timor-Leste,-8.874217,125.727539,1
8382,2020-03-31,NaN,Togo,8.619500,0.824800,34
8383,2020-03-31,NaN,Trinidad and Tobago,10.691800,-61.222500,87
8384,2020-03-31,NaN,Tunisia,34.000000,9.000000,394
8385,2020-03-31,NaN,Turkey,38.963700,35.243300,13531
8386,2020-03-31,NaN,US,37.090200,-95.712900,188172
8387,2020-03-31,NaN,Uganda,1.000000,32.000000,44
8388,2020-03-31,NaN,Ukraine,48.379400,31.165600,645
8389,2020-03-31,NaN,United Arab Emirates,24.000000,54.000000,664
8390,2020-03-31,NaN,United Kingdom,55.378100,-3.436000,25150
8391,2020-03-31,Anguilla,United Kingdom,18.220600,-63.068600,2
8392,2020-03-31,Bermuda,United Kingdom,32.307800,-64.750500,32
8393,2020-03-31,British Virgin Islands,United Kingdom,18.420700,-64.640000,3
8394,2020-03-31,Cayman Islands,United Kingdom,19.313300,-81.254600,14
8395,2020-03-31,Channel Islands,United Kingdom,49.372300,-2.364400,141
8396,2020-03-31,Gibraltar,United Kingdom,36.140800,-5.353600,69
8397,2020-03-31,Isle of Man,United Kingdom,54.236100,-4.548100,60
8398,2020-03-31,Montserrat,United Kingdom,16.742500,-62.187400,5
8399,2020-03-31,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,5
8400,2020-03-31,NaN,Uruguay,-32.522800,-55.765800,338
8401,2020-03-31,NaN,Uzbekistan,41.377500,64.585300,172
8402,2020-03-31,NaN,Venezuela,6.423800,-66.589700,135
8403,2020-03-31,NaN,Vietnam,16.000000,108.000000,212
8404,2020-03-31,NaN,West Bank and Gaza,31.952200,35.233200,119
8405,2020-03-31,NaN,Zambia,-15.416700,28.283300,35
8406,2020-03-31,NaN,Zimbabwe,-20.000000,30.000000,8

Pass "deaths" to get just counts of deaths, and "recovered" to get just counts of recovered cases. If you ask for an unavailable data type (e.g. passing "recovered" to the `get_data_nyt` function), the package will notify you and throw an exception.

## Dataframe format options
Our package provides the option of returning data tables in either the "wide" or "long" format. A "wide" format table has a separate column for every variable, whereas a "long" format table has one column for all variables. (See [this explanation](https://en.wikipedia.org/wiki/Wide_and_narrow_data) from Wikipedia for a more in-depth discussion of the differences.)

Many plotting tools prefer data in the "long" format. However, the "wide" format can also be useful, and sometimes makes data easier to think about. So, we provide both options. The actual data is the same either way; we just convert between the different formats for you.

Our package defaults to returning tables in the "long" format. To get a table in the "wide" format instead, pass`"wide"` to the `format` parameter in the getter function. 

Note: With a "wide" format table, you can only have one data type (cases, deaths, or recovered) in the table. So, you must pass an argument other that the default `"all"` to the `data_type` parameter. If you want multiple data types in the "wide" format, you need a separate table for each data type.