# Basic Usage Demo
This notebook goes over how to load data using the `covid19pandas` package. We will cover the many loading options available.

First, import the package.

In [1]:
import covid19pandas as cod

You can easily access data tables with just a single function call:

In [2]:
cod.get_data_jhu()

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,date,Province/State,Country/Region,Lat,Long,cases,deaths,recovered
0,2020-01-22,Anhui,China,31.825700,117.226400,1.0,0.0,0.0
1,2020-01-22,Beijing,China,40.182400,116.414200,14.0,0.0,0.0
2,2020-01-22,Chongqing,China,30.057200,107.874000,6.0,0.0,0.0
3,2020-01-22,Fujian,China,26.078900,117.987400,1.0,0.0,0.0
4,2020-01-22,Guangdong,China,23.341700,113.424400,26.0,0.0,0.0
5,2020-01-22,Guangxi,China,23.829800,108.788100,2.0,0.0,0.0
6,2020-01-22,Guizhou,China,26.815400,106.874800,1.0,0.0,0.0
7,2020-01-22,Hainan,China,19.195900,109.745300,4.0,0.0,0.0
8,2020-01-22,Hebei,China,39.549000,116.130600,1.0,0.0,0.0
9,2020-01-22,Henan,China,33.882000,113.614000,5.0,0.0,0.0
10,2020-01-22,Hubei,China,30.975600,112.270700,444.0,17.0,28.0
11,2020-01-22,Hunan,China,27.610400,111.708800,4.0,0.0,0.0
12,2020-01-22,Jiangsu,China,32.971100,119.455000,1.0,0.0,0.0
13,2020-01-22,Jiangxi,China,27.614000,115.722100,2.0,0.0,0.0
14,2020-01-22,Liaoning,China,41.295600,122.608500,2.0,0.0,0.0
15,2020-01-22,Macau,China,22.166700,113.550000,1.0,0.0,0.0
16,2020-01-22,Ningxia,China,37.269200,106.165500,1.0,0.0,0.0
17,2020-01-22,Shandong,China,36.342700,118.149800,2.0,0.0,0.0
18,2020-01-22,Shanghai,China,31.202000,121.449100,9.0,0.0,0.0
19,2020-01-22,Shanxi,China,37.577700,112.292200,1.0,0.0,0.0
20,2020-01-22,Sichuan,China,30.617100,102.710300,5.0,0.0,0.0
21,2020-01-22,Tianjin,China,39.305400,117.323000,4.0,0.0,0.0
22,2020-01-22,Yunnan,China,24.974000,101.487000,1.0,0.0,0.0
23,2020-01-22,Zhejiang,China,29.183200,120.093400,10.0,0.0,0.0
24,2020-01-22,NaN,Japan,36.000000,138.000000,2.0,0.0,0.0
25,2020-01-22,NaN,"Korea, South",36.000000,128.000000,1.0,0.0,0.0
26,2020-01-22,NaN,Taiwan*,23.700000,121.000000,1.0,0.0,0.0
27,2020-01-22,NaN,Thailand,15.000000,101.000000,2.0,0.0,0.0
28,2020-01-22,NaN,US,37.090200,-95.712900,1.0,0.0,0.0
29,2020-01-23,Anhui,China,31.825700,117.226400,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...
8436,2020-03-31,NaN,Syria,34.802075,38.996815,10.0,2.0,0.0
8437,2020-03-31,NaN,Taiwan*,23.700000,121.000000,322.0,5.0,39.0
8438,2020-03-31,NaN,Tanzania,-6.369000,34.888800,19.0,1.0,1.0
8439,2020-03-31,NaN,Thailand,15.000000,101.000000,1651.0,10.0,342.0
8440,2020-03-31,NaN,Timor-Leste,-8.874217,125.727539,1.0,0.0,0.0
8441,2020-03-31,NaN,Togo,8.619500,0.824800,34.0,1.0,10.0
8442,2020-03-31,NaN,Trinidad and Tobago,10.691800,-61.222500,87.0,3.0,1.0
8443,2020-03-31,NaN,Tunisia,34.000000,9.000000,394.0,10.0,3.0
8444,2020-03-31,NaN,Turkey,38.963700,35.243300,13531.0,214.0,243.0
8445,2020-03-31,NaN,US,37.090200,-95.712900,188172.0,3873.0,7024.0
8446,2020-03-31,NaN,Uganda,1.000000,32.000000,44.0,0.0,0.0
8447,2020-03-31,NaN,Ukraine,48.379400,31.165600,645.0,17.0,10.0
8448,2020-03-31,NaN,United Arab Emirates,24.000000,54.000000,664.0,6.0,61.0
8449,2020-03-31,NaN,United Kingdom,55.378100,-3.436000,25150.0,1789.0,135.0
8450,2020-03-31,Anguilla,United Kingdom,18.220600,-63.068600,2.0,0.0,0.0
8451,2020-03-31,Bermuda,United Kingdom,32.307800,-64.750500,32.0,0.0,10.0
8452,2020-03-31,British Virgin Islands,United Kingdom,18.420700,-64.640000,3.0,0.0,0.0
8453,2020-03-31,Cayman Islands,United Kingdom,19.313300,-81.254600,14.0,1.0,0.0
8454,2020-03-31,Channel Islands,United Kingdom,49.372300,-2.364400,141.0,3.0,0.0
8455,2020-03-31,Gibraltar,United Kingdom,36.140800,-5.353600,69.0,0.0,34.0
8456,2020-03-31,Isle of Man,United Kingdom,54.236100,-4.548100,60.0,0.0,0.0
8457,2020-03-31,Montserrat,United Kingdom,16.742500,-62.187400,5.0,0.0,0.0
8458,2020-03-31,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,5.0,0.0,0.0
8459,2020-03-31,NaN,Uruguay,-32.522800,-55.765800,338.0,1.0,41.0
8460,2020-03-31,NaN,Uzbekistan,41.377500,64.585300,172.0,2.0,7.0
8461,2020-03-31,NaN,Venezuela,6.423800,-66.589700,135.0,3.0,39.0
8462,2020-03-31,NaN,Vietnam,16.000000,108.000000,212.0,0.0,58.0
8463,2020-03-31,NaN,West Bank and Gaza,31.952200,35.233200,119.0,1.0,18.0
8464,2020-03-31,NaN,Zambia,-15.416700,28.283300,35.0,0.0,0.0
8465,2020-03-31,NaN,Zimbabwe,-20.000000,30.000000,8.0,1.0,0.0

In [3]:
cod.get_data_nyt()

These data were obtained from The New York Times (https://github.com/nytimes/covid-19-data).

            date                     state  fips  cases  deaths
0     2020-01-21                Washington    53      1       0
1     2020-01-22                Washington    53      1       0
2     2020-01-23                Washington    53      1       0
3     2020-01-24                  Illinois    17      1       0
4     2020-01-24                Washington    53      1       0
5     2020-01-25                California     6      1       0
6     2020-01-25                  Illinois    17      1       0
7     2020-01-25                Washington    53      1       0
8     2020-01-26                   Arizona     4      1       0
9     2020-01-26                California     6      2       0
10    2020-01-26                  Illinois    17      1       0
11    2020-01-26                Washington    53      1       0
12    2020-01-27                   Arizona     4      1       0
13    2020-01-27                California     6      2       0
14    2020-01-27                  Illinois    17      1       0
15    2020-01-27                Washington    53      1       0
16    2020-01-28                   Arizona     4      1       0
17    2020-01-28                California     6      2       0
18    2020-01-28                  Illinois    17      1       0
19    2020-01-28                Washington    53      1       0
20    2020-01-29                   Arizona     4      1       0
21    2020-01-29                California     6      2       0
22    2020-01-29                  Illinois    17      1       0
23    2020-01-29                Washington    53      1       0
24    2020-01-30                   Arizona     4      1       0
25    2020-01-30                California     6      2       0
26    2020-01-30                  Illinois    17      2       0
27    2020-01-30                Washington    53      1       0
28    2020-01-31                   Arizona     4      1       0
29    2020-01-31                California     6      3       0
...          ...                       ...   ...    ...     ...
1579  2020-03-31               Mississippi    28    937      20
1580  2020-03-31                  Missouri    29   1351      15
1581  2020-03-31                   Montana    30    198       5
1582  2020-03-31                  Nebraska    31    193       4
1583  2020-03-31                    Nevada    32   1113      26
1584  2020-03-31             New Hampshire    33    367       3
1585  2020-03-31                New Jersey    34  18696     267
1586  2020-03-31                New Mexico    35    315       4
1587  2020-03-31                  New York    36  75832    1550
1588  2020-03-31            North Carolina    37   1528      10
1589  2020-03-31              North Dakota    38    126       3
1590  2020-03-31  Northern Mariana Islands    69      2       0
1591  2020-03-31                      Ohio    39   2199      55
1592  2020-03-31                  Oklahoma    40    566      23
1593  2020-03-31                    Oregon    41    690      18
1594  2020-03-31              Pennsylvania    42   4997      72
1595  2020-03-31               Puerto Rico    72    239       8
1596  2020-03-31              Rhode Island    44    488       8
1597  2020-03-31            South Carolina    45   1083      22
1598  2020-03-31              South Dakota    46    108       1
1599  2020-03-31                 Tennessee    47   1834      13
1600  2020-03-31                     Texas    48   3576      57
1601  2020-03-31                      Utah    49    887       5
1602  2020-03-31                   Vermont    50    293      13
1603  2020-03-31            Virgin Islands    78     30       0
1604  2020-03-31                  Virginia    51   1250      27
1605  2020-03-31                Washington    53   5292     226
1606  2020-03-31             West Virginia    54    162       1
1607  2020-03-31                 Wisconsin    55   1351      25
1608  2020-03-31                   Wyoming    56    120       0

[1609 rows x 5 columns]

## Data source options
Our package provides access to data from both [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19) and [The New York Times](https://github.com/nytimes/covid-19-data). Here are some details about both datasets:
#### Johns Hopkins
- Function for access: `get_data_jhu`
- Provides both global and US data
- US data is broken down into states and counties
- For global data, provides confirmed cases, deaths, and recovered counts
- For US data, provides only confirmed cases and deaths counts.

#### The New York Times
- Function for access: `get_data_nyt`
- Provides only US data
- Has both state and county level data
- Provides confirmed cases and deaths counts.

We provide both data sources for comparison, as they aggregate data from different sources.

Note: Johns Hopkins [has stated](https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-606354840) that the reason they do not provide recovered counts for their US-specific data is that they cannot find a reliable source for recovered counts at the county level.

## Data type options
By default, our package will return all data types, meaning counts of both confirmed cases and deaths, and counts of recovered patients if available. You may want a table that only has one data type. To get a table with just one data type, pass that data type as a string to the `data_type` parameter. Pass `"cases"` to get counts of confirmed cases, `"deaths"` to get counts of deaths, or `"recovered"` to get counts of recoveries.

For example, to get just the counts of confirmed cases:

In [4]:
cod.get_data_jhu(data_type="cases")

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,date,Province/State,Country/Region,Lat,Long,cases
0,2020-01-22,Anhui,China,31.825700,117.226400,1
1,2020-01-22,Beijing,China,40.182400,116.414200,14
2,2020-01-22,Chongqing,China,30.057200,107.874000,6
3,2020-01-22,Fujian,China,26.078900,117.987400,1
4,2020-01-22,Guangdong,China,23.341700,113.424400,26
5,2020-01-22,Guangxi,China,23.829800,108.788100,2
6,2020-01-22,Guizhou,China,26.815400,106.874800,1
7,2020-01-22,Hainan,China,19.195900,109.745300,4
8,2020-01-22,Hebei,China,39.549000,116.130600,1
9,2020-01-22,Henan,China,33.882000,113.614000,5
10,2020-01-22,Hubei,China,30.975600,112.270700,444
11,2020-01-22,Hunan,China,27.610400,111.708800,4
12,2020-01-22,Jiangsu,China,32.971100,119.455000,1
13,2020-01-22,Jiangxi,China,27.614000,115.722100,2
14,2020-01-22,Liaoning,China,41.295600,122.608500,2
15,2020-01-22,Macau,China,22.166700,113.550000,1
16,2020-01-22,Ningxia,China,37.269200,106.165500,1
17,2020-01-22,Shandong,China,36.342700,118.149800,2
18,2020-01-22,Shanghai,China,31.202000,121.449100,9
19,2020-01-22,Shanxi,China,37.577700,112.292200,1
20,2020-01-22,Sichuan,China,30.617100,102.710300,5
21,2020-01-22,Tianjin,China,39.305400,117.323000,4
22,2020-01-22,Yunnan,China,24.974000,101.487000,1
23,2020-01-22,Zhejiang,China,29.183200,120.093400,10
24,2020-01-22,NaN,Japan,36.000000,138.000000,2
25,2020-01-22,NaN,"Korea, South",36.000000,128.000000,1
26,2020-01-22,NaN,Taiwan*,23.700000,121.000000,1
27,2020-01-22,NaN,Thailand,15.000000,101.000000,2
28,2020-01-22,NaN,US,37.090200,-95.712900,1
29,2020-01-23,Anhui,China,31.825700,117.226400,9
...,...,...,...,...,...,...
8377,2020-03-31,NaN,Syria,34.802075,38.996815,10
8378,2020-03-31,NaN,Taiwan*,23.700000,121.000000,322
8379,2020-03-31,NaN,Tanzania,-6.369000,34.888800,19
8380,2020-03-31,NaN,Thailand,15.000000,101.000000,1651
8381,2020-03-31,NaN,Timor-Leste,-8.874217,125.727539,1
8382,2020-03-31,NaN,Togo,8.619500,0.824800,34
8383,2020-03-31,NaN,Trinidad and Tobago,10.691800,-61.222500,87
8384,2020-03-31,NaN,Tunisia,34.000000,9.000000,394
8385,2020-03-31,NaN,Turkey,38.963700,35.243300,13531
8386,2020-03-31,NaN,US,37.090200,-95.712900,188172
8387,2020-03-31,NaN,Uganda,1.000000,32.000000,44
8388,2020-03-31,NaN,Ukraine,48.379400,31.165600,645
8389,2020-03-31,NaN,United Arab Emirates,24.000000,54.000000,664
8390,2020-03-31,NaN,United Kingdom,55.378100,-3.436000,25150
8391,2020-03-31,Anguilla,United Kingdom,18.220600,-63.068600,2
8392,2020-03-31,Bermuda,United Kingdom,32.307800,-64.750500,32
8393,2020-03-31,British Virgin Islands,United Kingdom,18.420700,-64.640000,3
8394,2020-03-31,Cayman Islands,United Kingdom,19.313300,-81.254600,14
8395,2020-03-31,Channel Islands,United Kingdom,49.372300,-2.364400,141
8396,2020-03-31,Gibraltar,United Kingdom,36.140800,-5.353600,69
8397,2020-03-31,Isle of Man,United Kingdom,54.236100,-4.548100,60
8398,2020-03-31,Montserrat,United Kingdom,16.742500,-62.187400,5
8399,2020-03-31,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,5
8400,2020-03-31,NaN,Uruguay,-32.522800,-55.765800,338
8401,2020-03-31,NaN,Uzbekistan,41.377500,64.585300,172
8402,2020-03-31,NaN,Venezuela,6.423800,-66.589700,135
8403,2020-03-31,NaN,Vietnam,16.000000,108.000000,212
8404,2020-03-31,NaN,West Bank and Gaza,31.952200,35.233200,119
8405,2020-03-31,NaN,Zambia,-15.416700,28.283300,35
8406,2020-03-31,NaN,Zimbabwe,-20.000000,30.000000,8

If you ask for an unavailable data type (e.g. passing `"recovered"` to the `get_data_nyt` function), the package will notify you and throw an exception. Passing `"all"` (the default argument) will return all available data types.

## Dataframe format options
Our package provides the option of returning data tables in either the wide or long format. A wide format table has a separate column for every variable, whereas a long format table has one column for all variables. (See [this explanation](https://en.wikipedia.org/wiki/Wide_and_narrow_data) from Wikipedia for a more in-depth discussion of the differences.)

Many plotting tools prefer data in the long format. However, the wide format can also be useful, and sometimes makes data easier to think about. So, we provide both options. The actual data is the same either way; we just convert between the different formats for you.

Our package defaults to returning tables in the long format. To get a table in the wide format instead, pass `"wide"` to the `format` parameter in the getter function. With a wide format table, you can only have one data type (cases, deaths, or recovered) in the table. So, you must pass an argument other that the default `"all"` to the `data_type` parameter. If you want multiple data types in the wide format, you need a separate table for each data type.

In [5]:
cod.get_data_jhu(format="wide", data_type="cases")

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,Province/State,Country/Region,Lat,Long,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2020-03-22,2020-03-23,2020-03-24,2020-03-25,2020-03-26,2020-03-27,2020-03-28,2020-03-29,2020-03-30,2020-03-31
0,NaN,Afghanistan,33.000000,65.000000,0,0,0,0,0,0,...,40,40,74,84,94,110,110,120,170,174
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,89,104,123,146,174,186,197,212,223,243
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,201,230,264,302,367,409,454,511,584,716
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,113,133,164,188,224,267,308,334,370,376
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,2,3,3,3,4,4,5,7,7,7
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,1,3,3,3,7,7,7,7,7,7
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,266,301,387,387,502,589,690,745,820,1054
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,194,235,249,265,290,329,407,424,482,532
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,19,32,39,39,53,62,71,77,78,80
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,3,4,...,669,669,818,1029,1219,1405,1617,1791,2032,2032
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,5,5,6,6,12,12,15,15,15,17
11,Queensland,Australia,-28.016700,153.400000,0,0,0,0,0,0,...,259,319,397,443,493,555,625,656,689,743
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,100,134,170,170,235,257,287,299,305,337
13,Tasmania,Australia,-41.454500,145.970700,0,0,0,0,0,0,...,22,28,28,36,47,47,62,66,66,69
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,1,1,...,355,355,411,466,520,574,685,769,821,917
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,120,140,175,175,231,231,278,311,355,364
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,3582,4474,5283,5588,6909,7657,8271,8788,9618,10180
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,65,72,87,93,122,165,182,209,273,298
18,NaN,Bahamas,25.034300,-77.396300,0,0,0,0,0,0,...,4,4,5,5,9,10,10,11,14,14
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,334,377,392,419,458,466,476,499,515,567
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,27,33,39,39,44,48,48,48,49,51
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,14,17,18,18,18,24,26,33,33,34
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,76,81,81,86,86,94,94,94,152,152
23,NaN,Belgium,50.833300,4.000000,0,0,0,0,0,0,...,3401,3743,4269,4937,6235,7284,9134,10836,11899,12775
24,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,2,5,6,6,6,6,6,6,6,9
25,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,2,2,2,2,2,3,3,4,4,4
26,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,24,27,29,32,43,61,74,81,97,107
27,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,126,136,166,176,191,237,258,323,368,420
28,NaN,Brazil,-14.235000,-51.925300,0,0,0,0,0,0,...,1546,1924,2247,2554,2985,3417,3904,4256,4579,5717
29,NaN,Brunei,4.535300,114.727700,0,0,0,0,0,0,...,88,91,104,109,114,115,120,126,127,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,NaN,Uzbekistan,41.377500,64.585300,0,0,0,0,0,0,...,43,46,50,60,75,88,104,144,149,172
227,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,70,77,84,91,107,107,119,119,135,135
228,NaN,Vietnam,16.000000,108.000000,0,2,2,2,2,2,...,113,123,134,141,153,163,174,188,203,212
229,NaN,Zambia,-15.416700,28.283300,0,0,0,0,0,0,...,3,3,3,12,16,22,28,29,35,35
230,NaN,Zimbabwe,-20.000000,30.000000,0,0,0,0,0,0,...,3,3,3,3,3,5,7,7,7,8
231,Diamond Princess,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
232,NaN,Dominica,15.415000,-61.371000,0,0,0,0,0,0,...,1,2,2,7,11,11,11,11,11,12
233,NaN,Grenada,12.116500,-61.679000,0,0,0,0,0,0,...,1,1,1,1,7,7,7,9,9,9
234,NaN,Mozambique,-18.665695,35.529562,0,0,0,0,0,0,...,1,1,3,5,7,7,8,8,8,8
235,NaN,Syria,34.802075,38.996815,0,0,0,0,0,0,...,1,1,1,5,5,5,5,9,10,10
236,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
237,NaN,Belize,13.193900,-59.543200,0,0,0,0,0,0,...,0,1,1,2,2,2,2,2,3,3
238,Recovered,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,NaN,Laos,19.856270,102.495496,0,0,0,0,0,0,...,0,0,2,3,6,6,8,8,8,9
240,NaN,Libya,26.335100,17.228331,0,0,0,0,0,0,...,0,0,1,1,1,1,3,8,8,10
241,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,52,59,59,59,84,91,98,109,116,119
242,NaN,Guinea-Bissau,11.803700,-15.180400,0,0,0,0,0,0,...,0,0,0,2,2,2,2,2,8,8
243,NaN,Mali,17.570692,-3.996166,0,0,0,0,0,0,...,0,0,0,2,4,11,18,18,25,28
244,NaN,Saint Kitts and Nevis,17.357822,-62.782998,0,0,0,0,0,0,...,0,0,0,2,2,2,2,2,7,8
245,Northwest Territories,Canada,64.825500,-124.845700,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
246,Yukon,Canada,64.282300,-135.000000,0,0,0,0,0,0,...,0,0,0,0,3,3,4,4,4,5
247,NaN,Kosovo,42.602636,20.902977,0,0,0,0,0,0,...,0,0,0,0,71,86,91,94,94,112
248,NaN,Burma,21.916200,95.956000,0,0,0,0,0,0,...,0,0,0,0,0,8,8,10,14,15
249,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,2
250,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,3
251,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,0,0,0,0,0,0,4,4,5,5
252,NaN,MS Zaandam,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,2
253,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,4
254,NaN,Burundi,-3.373100,29.918900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
255,NaN,Sierra Leone,8.460555,-11.779889,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

Note how each date (each variable) now has its own column.

## JHU Data: Region options
Johns Hopkins provides both global and US data. The global data is organized by country, but broken down into states or provinces where possible. The US data is organized by county. Global data includes recovered counts, as well as cases and deaths, but the US data only includes cases and deaths. Both tables include latitude and longitude for mapping each sample, and the US table includes additional geographical identifiers.

The `get_data_jhu` function defaults to returning global data. To get US data, pass `"us"` to the `region` parameter.

In [6]:
cod.get_data_jhu(region="us")

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,date,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long,Combined_Key,Population,cases,deaths
0,2020-01-22,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
1,2020-01-23,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
2,2020-01-24,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
3,2020-01-24,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
4,2020-01-25,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
5,2020-01-25,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
6,2020-01-26,84004013,US,USA,840,4013.0,Maricopa,Arizona,US,33.348359,-112.491815,"Maricopa, Arizona, US",NaN,1.0,0.0
7,2020-01-26,84006037,US,USA,840,6037.0,Los Angeles,California,US,34.308284,-118.228241,"Los Angeles, California, US",NaN,1.0,0.0
8,2020-01-26,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,"Orange, California, US",NaN,1.0,0.0
9,2020-01-26,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
10,2020-01-26,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
11,2020-01-27,84004013,US,USA,840,4013.0,Maricopa,Arizona,US,33.348359,-112.491815,"Maricopa, Arizona, US",NaN,1.0,0.0
12,2020-01-27,84006037,US,USA,840,6037.0,Los Angeles,California,US,34.308284,-118.228241,"Los Angeles, California, US",NaN,1.0,0.0
13,2020-01-27,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,"Orange, California, US",NaN,1.0,0.0
14,2020-01-27,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
15,2020-01-27,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
16,2020-01-28,84004013,US,USA,840,4013.0,Maricopa,Arizona,US,33.348359,-112.491815,"Maricopa, Arizona, US",NaN,1.0,0.0
17,2020-01-28,84006037,US,USA,840,6037.0,Los Angeles,California,US,34.308284,-118.228241,"Los Angeles, California, US",NaN,1.0,0.0
18,2020-01-28,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,"Orange, California, US",NaN,1.0,0.0
19,2020-01-28,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
20,2020-01-28,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
21,2020-01-29,84004013,US,USA,840,4013.0,Maricopa,Arizona,US,33.348359,-112.491815,"Maricopa, Arizona, US",NaN,1.0,0.0
22,2020-01-29,84006037,US,USA,840,6037.0,Los Angeles,California,US,34.308284,-118.228241,"Los Angeles, California, US",NaN,1.0,0.0
23,2020-01-29,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,"Orange, California, US",NaN,1.0,0.0
24,2020-01-29,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
25,2020-01-29,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,"King, Washington, US",NaN,1.0,0.0
26,2020-01-30,84004013,US,USA,840,4013.0,Maricopa,Arizona,US,33.348359,-112.491815,"Maricopa, Arizona, US",NaN,1.0,0.0
27,2020-01-30,84006037,US,USA,840,6037.0,Los Angeles,California,US,34.308284,-118.228241,"Los Angeles, California, US",NaN,1.0,0.0
28,2020-01-30,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,"Orange, California, US",NaN,1.0,0.0
29,2020-01-30,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,"Cook, Illinois, US",NaN,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21245,2020-03-30,84088888,US,USA,840,88888.0,NaN,Diamond Princess,US,0.000000,0.000000,"Diamond Princess, US",NaN,49.0,0.0
21246,2020-03-30,84090002,US,USA,840,90002.0,Unassigned,Alaska,US,0.000000,0.000000,"Unassigned, Alaska, US",0.0,0.0,2.0
21247,2020-03-30,84090004,US,USA,840,90004.0,Unassigned,Arizona,US,0.000000,0.000000,"Unassigned, Arizona, US",0.0,0.0,9.0
21248,2020-03-30,84090005,US,USA,840,90005.0,Unassigned,Arkansas,US,0.000000,0.000000,"Unassigned, Arkansas, US",0.0,49.0,2.0
21249,2020-03-30,84090008,US,USA,840,90008.0,Unassigned,Colorado,US,0.000000,0.000000,"Unassigned, Colorado, US",0.0,186.0,1.0
21250,2020-03-30,84090009,US,USA,840,90009.0,Unassigned,Connecticut,US,0.000000,0.000000,"Unassigned, Connecticut, US",NaN,176.0,0.0
21251,2020-03-30,84090012,US,USA,840,90012.0,Unassigned,Florida,US,0.000000,0.000000,"Unassigned, Florida, US",0.0,1.0,4.0
21252,2020-03-30,84090013,US,USA,840,90013.0,Unassigned,Georgia,US,0.000000,0.000000,"Unassigned, Georgia, US",0.0,164.0,1.0
21253,2020-03-30,84090015,US,USA,840,90015.0,Unassigned,Hawaii,US,0.000000,0.000000,"Unassigned, Hawaii, US",NaN,8.0,0.0
21254,2020-03-30,84090017,US,USA,840,90017.0,Unassigned,Illinois,US,0.000000,0.000000,"Unassigned, Illinois, US",NaN,13.0,0.0
21255,2020-03-30,84090021,US,USA,840,90021.0,Unassigned,Kentucky,US,0.000000,0.000000,"Unassigned, Kentucky, US",0.0,53.0,2.0
21256,2020-03-30,84090022,US,USA,840,90022.0,Unassigned,Louisiana,US,0.000000,0.000000,"Unassigned, Louisiana, US",NaN,14.0,0.0
21257,2020-03-30,84090023,US,USA,840,90023.0,Unassigned,Maine,US,0.000000,0.000000,"Unassigned, Maine, US",NaN,5.0,0.0
21258,2020-03-30,84090024,US,USA,840,90024.0,Unassigned,Maryland,US,0.000000,0.000000,"Unassigned, Maryland, US",0.0,0.0,1.0
21259,2020-03-30,84090025,US,USA,840,90025.0,Unassigned,Massachusetts,US,0.000000,0.000000,"Unassigned, Massachusetts, US",0.0,489.0,9.0
21260,2020-03-30,84090026,US,USA,840,90026.0,Unassigned,Michigan,US,0.000000,0.000000,"Unassigned, Michigan, US",NaN,78.0,0.0
21261,2020-03-30,84090027,US,USA,840,90027.0,Unassigned,Minnesota,US,0.000000,0.000000,"Unassigned, Minnesota, US",0.0,0.0,1.0
21262,2020-03-30,84090028,US,USA,840,90028.0,Unassigned,Mississippi,US,0.000000,0.000000,"Unassigned, Mississippi, US",0.0,89.0,2.0
21263,2020-03-30,84090031,US,USA,840,90031.0,Unassigned,Nebraska,US,0.000000,0.000000,"Unassigned, Nebraska, US",NaN,2.0,0.0
21264,2020-03-30,84090032,US,USA,840,90032.0,Unassigned,Nevada,US,0.000000,0.000000,"Unassigned, Nevada, US",NaN,132.0,0.0
21265,2020-03-30,84090033,US,USA,840,90033.0,Unassigned,New Hampshire,US,0.000000,0.000000,"Unassigned, New Hampshire, US",NaN,56.0,0.0
21266,2020-03-30,84090034,US,USA,840,90034.0,Unassigned,New Jersey,US,0.000000,0.000000,"Unassigned, New Jersey, US",0.0,3847.0,91.0
21267,2020-03-30,84090036,US,USA,840,90036.0,Unassigned,New York,US,0.000000,0.000000,"Unassigned, New York, US",0.0,0.0,298.0
21268,2020-03-30,84090037,US,USA,840,90037.0,Unassigned,North Carolina,US,0.000000,0.000000,"Unassigned, North Carolina, US",0.0,0.0,1.0
21269,2020-03-30,84090038,US,USA,840,90038.0,Unassigned,North Dakota,US,0.000000,0.000000,"Unassigned, North Dakota, US",0.0,0.0,1.0
21270,2020-03-30,84090044,US,USA,840,90044.0,Unassigned,Rhode Island,US,0.000000,0.000000,"Unassigned, Rhode Island, US",0.0,171.0,4.0
21271,2020-03-30,84090047,US,USA,840,90047.0,Unassigned,Tennessee,US,0.000000,0.000000,"Unassigned, Tennessee, US",0.0,197.0,4.0
21272,2020-03-30,84090050,US,USA,840,90050.0,Unassigned,Vermont,US,0.000000,0.000000,"Unassigned, Vermont, US",0.0,28.0,7.0
21273,2020-03-30,84090053,US,USA,840,90053.0,Unassigned,Washington,US,0.000000,0.000000,"Unassigned, Washington, US",NaN,274.0,0.0
21274,2020-03-30,84099999,US,USA,840,99999.0,NaN,Grand Princess,US,0.000000,0.000000,"Grand Princess, US",0.0,103.0,3.0

## NYT Data: County option
The New York Times provides both state and county level data for the US. Both types incude just counts for confirmed cases and deaths. The tables include (FIPS codes)[https://www.census.gov/quickfacts/fact/note/US/fips] with each row for geographical identification.

The `get_data_nyt` function defaults to state level data. To get county level data, pass `True` to the `counties` parameter.

In [7]:
cod.get_data_nyt(counties=True)

These data were obtained from The New York Times (https://github.com/nytimes/covid-19-data).

             date       county       state     fips  cases  deaths
0      2020-01-21    Snohomish  Washington  53061.0      1       0
1      2020-01-22    Snohomish  Washington  53061.0      1       0
2      2020-01-23    Snohomish  Washington  53061.0      1       0
3      2020-01-24         Cook    Illinois  17031.0      1       0
4      2020-01-24    Snohomish  Washington  53061.0      1       0
5      2020-01-25       Orange  California   6059.0      1       0
6      2020-01-25         Cook    Illinois  17031.0      1       0
7      2020-01-25    Snohomish  Washington  53061.0      1       0
8      2020-01-26     Maricopa     Arizona   4013.0      1       0
9      2020-01-26  Los Angeles  California   6037.0      1       0
10     2020-01-26       Orange  California   6059.0      1       0
11     2020-01-26         Cook    Illinois  17031.0      1       0
12     2020-01-26    Snohomish  Washington  53061.0      1       0
13     2020-01-27     Maricopa     Arizona   4013.0      1       0
14     2020-01-27  Los Angeles  California   6037.0      1       0
15     2020-01-27       Orange  California   6059.0      1       0
16     2020-01-27         Cook    Illinois  17031.0      1       0
17     2020-01-27    Snohomish  Washington  53061.0      1       0
18     2020-01-28     Maricopa     Arizona   4013.0      1       0
19     2020-01-28  Los Angeles  California   6037.0      1       0
20     2020-01-28       Orange  California   6059.0      1       0
21     2020-01-28         Cook    Illinois  17031.0      1       0
22     2020-01-28    Snohomish  Washington  53061.0      1       0
23     2020-01-29     Maricopa     Arizona   4013.0      1       0
24     2020-01-29  Los Angeles  California   6037.0      1       0
25     2020-01-29       Orange  California   6059.0      1       0
26     2020-01-29         Cook    Illinois  17031.0      1       0
27     2020-01-29    Snohomish  Washington  53061.0      1       0
28     2020-01-30     Maricopa     Arizona   4013.0      1       0
29     2020-01-30  Los Angeles  California   6037.0      1       0
...           ...          ...         ...      ...    ...     ...
23937  2020-03-31      Portage   Wisconsin  55097.0      1       0
23938  2020-03-31       Racine   Wisconsin  55101.0     26       0
23939  2020-03-31     Richland   Wisconsin  55103.0      2       0
23940  2020-03-31         Rock   Wisconsin  55105.0     16       0
23941  2020-03-31         Sauk   Wisconsin  55111.0     13       1
23942  2020-03-31    Sheboygan   Wisconsin  55117.0     11       0
23943  2020-03-31    St. Croix   Wisconsin  55109.0      5       0
23944  2020-03-31        Vilas   Wisconsin  55125.0      3       0
23945  2020-03-31     Walworth   Wisconsin  55127.0      6       0
23946  2020-03-31   Washington   Wisconsin  55131.0     40       1
23947  2020-03-31     Waukesha   Wisconsin  55133.0    101       1
23948  2020-03-31      Waupaca   Wisconsin  55135.0      1       1
23949  2020-03-31    Winnebago   Wisconsin  55139.0     11       0
23950  2020-03-31         Wood   Wisconsin  55141.0      2       0
23951  2020-03-31       Albany     Wyoming  56001.0      3       0
23952  2020-03-31     Campbell     Wyoming  56005.0      3       0
23953  2020-03-31       Carbon     Wyoming  56007.0      3       0
23954  2020-03-31     Converse     Wyoming  56009.0      1       0
23955  2020-03-31      Fremont     Wyoming  56013.0     25       0
23956  2020-03-31       Goshen     Wyoming  56015.0      1       0
23957  2020-03-31  Hot Springs     Wyoming  56017.0      1       0
23958  2020-03-31      Johnson     Wyoming  56019.0      7       0
23959  2020-03-31      Laramie     Wyoming  56021.0     27       0
23960  2020-03-31      Natrona     Wyoming  56025.0     12       0
23961  2020-03-31         Park     Wyoming  56029.0      1       0
23962  2020-03-31     Sheridan     Wyoming  56033.0     10       0
23963  2020-03-31     Sublette     Wyoming  56035.0      1       0
23964  2020-03-31   Sweetwater     Wyoming  56037.0      2       0
23965  2020-03-31        Teton     Wyoming  56039.0     23       0
23966  2020-03-31     Washakie     Wyoming  56043.0      1       0

[23967 rows x 6 columns]

## Update options
By default, every time you load a table, the package will send a web request to the original source of the table and re-download it, to make sure you have the most up-to-date version of the table. This normally does not take very long. Each time you load a table, the package saves a copy of it on your local machine, so that you can still load the table later even if you are somewhere without internet connection.

However, you may want to skip this update option to avoid small changes in the data you're working with. It could also speed things up if you have a slow internet connection. To skip the data update step, pass `False` to the `update` parameter when you load the table. The package will warn you that the table has not been updated.

In [8]:
cod.get_data_jhu(update=False)

Warning: You chose to not update data files. Data from most recent download will be used. To update files instead, pass True to the 'update' parameter. (/home/caleb/anaconda3/envs/paynelab/lib/python3.7/site-packages/ipykernel_launcher.py, line 1)

These data were obtained from Johns Hopkins University (https://github.com/CSSEGISandData/COVID-19).

,date,Province/State,Country/Region,Lat,Long,cases,deaths,recovered
0,2020-01-22,Anhui,China,31.825700,117.226400,1.0,0.0,0.0
1,2020-01-22,Beijing,China,40.182400,116.414200,14.0,0.0,0.0
2,2020-01-22,Chongqing,China,30.057200,107.874000,6.0,0.0,0.0
3,2020-01-22,Fujian,China,26.078900,117.987400,1.0,0.0,0.0
4,2020-01-22,Guangdong,China,23.341700,113.424400,26.0,0.0,0.0
5,2020-01-22,Guangxi,China,23.829800,108.788100,2.0,0.0,0.0
6,2020-01-22,Guizhou,China,26.815400,106.874800,1.0,0.0,0.0
7,2020-01-22,Hainan,China,19.195900,109.745300,4.0,0.0,0.0
8,2020-01-22,Hebei,China,39.549000,116.130600,1.0,0.0,0.0
9,2020-01-22,Henan,China,33.882000,113.614000,5.0,0.0,0.0
10,2020-01-22,Hubei,China,30.975600,112.270700,444.0,17.0,28.0
11,2020-01-22,Hunan,China,27.610400,111.708800,4.0,0.0,0.0
12,2020-01-22,Jiangsu,China,32.971100,119.455000,1.0,0.0,0.0
13,2020-01-22,Jiangxi,China,27.614000,115.722100,2.0,0.0,0.0
14,2020-01-22,Liaoning,China,41.295600,122.608500,2.0,0.0,0.0
15,2020-01-22,Macau,China,22.166700,113.550000,1.0,0.0,0.0
16,2020-01-22,Ningxia,China,37.269200,106.165500,1.0,0.0,0.0
17,2020-01-22,Shandong,China,36.342700,118.149800,2.0,0.0,0.0
18,2020-01-22,Shanghai,China,31.202000,121.449100,9.0,0.0,0.0
19,2020-01-22,Shanxi,China,37.577700,112.292200,1.0,0.0,0.0
20,2020-01-22,Sichuan,China,30.617100,102.710300,5.0,0.0,0.0
21,2020-01-22,Tianjin,China,39.305400,117.323000,4.0,0.0,0.0
22,2020-01-22,Yunnan,China,24.974000,101.487000,1.0,0.0,0.0
23,2020-01-22,Zhejiang,China,29.183200,120.093400,10.0,0.0,0.0
24,2020-01-22,NaN,Japan,36.000000,138.000000,2.0,0.0,0.0
25,2020-01-22,NaN,"Korea, South",36.000000,128.000000,1.0,0.0,0.0
26,2020-01-22,NaN,Taiwan*,23.700000,121.000000,1.0,0.0,0.0
27,2020-01-22,NaN,Thailand,15.000000,101.000000,2.0,0.0,0.0
28,2020-01-22,NaN,US,37.090200,-95.712900,1.0,0.0,0.0
29,2020-01-23,Anhui,China,31.825700,117.226400,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...
8436,2020-03-31,NaN,Syria,34.802075,38.996815,10.0,2.0,0.0
8437,2020-03-31,NaN,Taiwan*,23.700000,121.000000,322.0,5.0,39.0
8438,2020-03-31,NaN,Tanzania,-6.369000,34.888800,19.0,1.0,1.0
8439,2020-03-31,NaN,Thailand,15.000000,101.000000,1651.0,10.0,342.0
8440,2020-03-31,NaN,Timor-Leste,-8.874217,125.727539,1.0,0.0,0.0
8441,2020-03-31,NaN,Togo,8.619500,0.824800,34.0,1.0,10.0
8442,2020-03-31,NaN,Trinidad and Tobago,10.691800,-61.222500,87.0,3.0,1.0
8443,2020-03-31,NaN,Tunisia,34.000000,9.000000,394.0,10.0,3.0
8444,2020-03-31,NaN,Turkey,38.963700,35.243300,13531.0,214.0,243.0
8445,2020-03-31,NaN,US,37.090200,-95.712900,188172.0,3873.0,7024.0
8446,2020-03-31,NaN,Uganda,1.000000,32.000000,44.0,0.0,0.0
8447,2020-03-31,NaN,Ukraine,48.379400,31.165600,645.0,17.0,10.0
8448,2020-03-31,NaN,United Arab Emirates,24.000000,54.000000,664.0,6.0,61.0
8449,2020-03-31,NaN,United Kingdom,55.378100,-3.436000,25150.0,1789.0,135.0
8450,2020-03-31,Anguilla,United Kingdom,18.220600,-63.068600,2.0,0.0,0.0
8451,2020-03-31,Bermuda,United Kingdom,32.307800,-64.750500,32.0,0.0,10.0
8452,2020-03-31,British Virgin Islands,United Kingdom,18.420700,-64.640000,3.0,0.0,0.0
8453,2020-03-31,Cayman Islands,United Kingdom,19.313300,-81.254600,14.0,1.0,0.0
8454,2020-03-31,Channel Islands,United Kingdom,49.372300,-2.364400,141.0,3.0,0.0
8455,2020-03-31,Gibraltar,United Kingdom,36.140800,-5.353600,69.0,0.0,34.0
8456,2020-03-31,Isle of Man,United Kingdom,54.236100,-4.548100,60.0,0.0,0.0
8457,2020-03-31,Montserrat,United Kingdom,16.742500,-62.187400,5.0,0.0,0.0
8458,2020-03-31,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,5.0,0.0,0.0
8459,2020-03-31,NaN,Uruguay,-32.522800,-55.765800,338.0,1.0,41.0
8460,2020-03-31,NaN,Uzbekistan,41.377500,64.585300,172.0,2.0,7.0
8461,2020-03-31,NaN,Venezuela,6.423800,-66.589700,135.0,3.0,39.0
8462,2020-03-31,NaN,Vietnam,16.000000,108.000000,212.0,0.0,58.0
8463,2020-03-31,NaN,West Bank and Gaza,31.952200,35.233200,119.0,1.0,18.0
8464,2020-03-31,NaN,Zambia,-15.416700,28.283300,35.0,0.0,0.0
8465,2020-03-31,NaN,Zimbabwe,-20.000000,30.000000,8.0,1.0,0.0